// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.us-central1.gcp.commercetools.com") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Query custom objects
    #
    # + projectKey - The `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A paged list of custom objects 
    remote isolated function listCustomObjects(string projectKey, map<string|string[]> headers = {}, *ListCustomObjectsQueries queries) returns CustomObjectPagedQueryResponse|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/custom-objects`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}, "sort": {style: FORM, explode: true}, "where": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create or update a custom object
    #
    # + projectKey - The `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Custom object draft with container, key, value and optional version 
    # + return - The updated custom object 
    remote isolated function createOrUpdateCustomObject(string projectKey, CustomObjectDraft payload, map<string|string[]> headers = {}, *CreateOrUpdateCustomObjectQueries queries) returns CustomObject|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/custom-objects`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Query custom objects in a container
    #
    # + projectKey - The `key` of the Project
    # + container - The container of the Custom Objects
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A paged list of custom objects in the container 
    remote isolated function listCustomObjectsByContainer(string projectKey, string container, map<string|string[]> headers = {}, *ListCustomObjectsByContainerQueries queries) returns CustomObjectPagedQueryResponse|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/custom-objects/${getEncodedUri(container)}`;
        map<Encoding> queryParamEncoding = {"sort": {style: FORM, explode: true}, "where": {style: FORM, explode: true}, "expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get a custom object by container and key
    #
    # + projectKey - The `key` of the Project
    # + container - The container of the Custom Objects
    # + 'key - User-defined unique identifier of the resource (or of the Custom Object within its container)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested custom object 
    remote isolated function getCustomObjectByContainerAndKey(string projectKey, string container, string 'key, map<string|string[]> headers = {}, *GetCustomObjectByContainerAndKeyQueries queries) returns CustomObject|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/custom-objects/${getEncodedUri(container)}/${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete a custom object by container and key
    #
    # + projectKey - The `key` of the Project
    # + container - The container of the Custom Objects
    # + 'key - User-defined unique identifier of the resource (or of the Custom Object within its container)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted custom object 
    remote isolated function deleteCustomObjectByContainerAndKey(string projectKey, string container, string 'key, map<string|string[]> headers = {}, *DeleteCustomObjectByContainerAndKeyQueries queries) returns CustomObject|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/custom-objects/${getEncodedUri(container)}/${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Query product types
    #
    # + projectKey - The `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A paged list of product types 
    remote isolated function listProductTypes(string projectKey, map<string|string[]> headers = {}, *ListProductTypesQueries queries) returns ProductTypePagedQueryResponse|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-types`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}, "sort": {style: FORM, explode: true}, "where": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a product type
    #
    # + projectKey - The `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Product type draft with key, name, description and attribute definitions 
    # + return - The created product type 
    remote isolated function createProductType(string projectKey, ProductTypeDraft payload, map<string|string[]> headers = {}, *CreateProductTypeQueries queries) returns ProductType|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-types`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a product type by key
    #
    # + projectKey - The `key` of the Project
    # + 'key - User-defined unique identifier of the resource (or of the Custom Object within its container)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested product type 
    remote isolated function getProductTypeByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *GetProductTypeByKeyQueries queries) returns ProductType|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-types/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a product type by key
    #
    # + projectKey - The `key` of the Project
    # + 'key - User-defined unique identifier of the resource (or of the Custom Object within its container)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions to apply to the product type identified by key 
    # + return - The updated product type 
    remote isolated function updateProductTypeByKey(string projectKey, string 'key, ProductTypeUpdate payload, map<string|string[]> headers = {}, *UpdateProductTypeByKeyQueries queries) returns ProductType|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-types/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a product type by key
    #
    # + projectKey - The `key` of the Project
    # + 'key - User-defined unique identifier of the resource (or of the Custom Object within its container)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted product type 
    remote isolated function deleteProductTypeByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *DeleteProductTypeByKeyQueries queries) returns ProductType|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-types/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get a product type by ID
    #
    # + projectKey - The `key` of the Project
    # + id - System-generated unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested product type 
    remote isolated function getProductTypeById(string projectKey, string id, map<string|string[]> headers = {}, *GetProductTypeByIdQueries queries) returns ProductType|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-types/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a product type by ID
    #
    # + projectKey - The `key` of the Project
    # + id - System-generated unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions to apply to the product type identified by ID 
    # + return - The updated product type 
    remote isolated function updateProductTypeById(string projectKey, string id, ProductTypeUpdate payload, map<string|string[]> headers = {}, *UpdateProductTypeByIdQueries queries) returns ProductType|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-types/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a product type by ID
    #
    # + projectKey - The `key` of the Project
    # + id - System-generated unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted product type 
    remote isolated function deleteProductTypeById(string projectKey, string id, map<string|string[]> headers = {}, *DeleteProductTypeByIdQueries queries) returns ProductType|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/product-types/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Query types
    #
    # + projectKey - The `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A paged list of types 
    remote isolated function listTypes(string projectKey, map<string|string[]> headers = {}, *ListTypesQueries queries) returns TypePagedQueryResponse|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/types`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}, "sort": {style: FORM, explode: true}, "where": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create a type
    #
    # + projectKey - The `key` of the Project
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Type draft with key, name, resource type IDs and field definitions 
    # + return - The created type 
    remote isolated function createType(string projectKey, TypeDraft payload, map<string|string[]> headers = {}, *CreateTypeQueries queries) returns Type|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/types`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get a type by key
    #
    # + projectKey - The `key` of the Project
    # + 'key - User-defined unique identifier of the resource (or of the Custom Object within its container)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested type 
    remote isolated function getTypeByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *GetTypeByKeyQueries queries) returns Type|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/types/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a type by key
    #
    # + projectKey - The `key` of the Project
    # + 'key - User-defined unique identifier of the resource (or of the Custom Object within its container)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions to apply to the type identified by key 
    # + return - The updated type 
    remote isolated function updateTypeByKey(string projectKey, string 'key, TypeUpdate payload, map<string|string[]> headers = {}, *UpdateTypeByKeyQueries queries) returns Type|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/types/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a type by key
    #
    # + projectKey - The `key` of the Project
    # + 'key - User-defined unique identifier of the resource (or of the Custom Object within its container)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted type 
    remote isolated function deleteTypeByKey(string projectKey, string 'key, map<string|string[]> headers = {}, *DeleteTypeByKeyQueries queries) returns Type|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/types/key=${getEncodedUri('key)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get a type by ID
    #
    # + projectKey - The `key` of the Project
    # + id - System-generated unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested type 
    remote isolated function getTypeById(string projectKey, string id, map<string|string[]> headers = {}, *GetTypeByIdQueries queries) returns Type|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/types/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a type by ID
    #
    # + projectKey - The `key` of the Project
    # + id - System-generated unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Version and update actions to apply to the type identified by ID 
    # + return - The updated type 
    remote isolated function updateTypeById(string projectKey, string id, TypeUpdate payload, map<string|string[]> headers = {}, *UpdateTypeByIdQueries queries) returns Type|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/types/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete a type by ID
    #
    # + projectKey - The `key` of the Project
    # + id - System-generated unique identifier of the resource
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The deleted type 
    remote isolated function deleteTypeById(string projectKey, string id, map<string|string[]> headers = {}, *DeleteTypeByIdQueries queries) returns Type|error {
        string resourcePath = string `/${getEncodedUri(projectKey)}/types/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->delete(resourcePath, headers = headers);
    }
}
