// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type Locale string;

public type StoreKeyReference record {
    *KeyReference;
    ReferenceTypeId typeId;
    string 'key;
};

# OAuth2 Client Credentials Grant Configs
public type OAuth2ClientCredentialsGrantConfig record {|
    *http:OAuth2ClientCredentialsGrantConfig;
    # Token URL
    string tokenUrl = "https://auth.us-central1.gcp.commercetools.com/oauth/token";
|};

public type Address record {
    *BaseAddress;
    CountryCode country?;
    string lastName?;
    string city?;
    string postalCode?;
    string title?;
    string building?;
    string streetName?;
    string company?;
    string id?;
    string state?;
    string department?;
    string fax?;
    string 'key?;
    string email?;
    string pOBox?;
    string streetNumber?;
    CustomFields custom?;
    string mobile?;
    string externalId?;
    string additionalAddressInfo?;
    string firstName?;
    string phone?;
    string additionalStreetInfo?;
    string salutation?;
    string region?;
    string apartment?;
};

public type KeyReference record {
    ReferenceTypeId typeId;
    string 'key;
};

public type Customer record {
    *BaseResource;
    string lastName?;
    Address[] addresses;
    string lastModifiedAt;
    string companyName?;
    string vatId?;
    string title?;
    Locale locale?;
    string[] shippingAddressIds;
    boolean isEmailVerified;
    string createdAt;
    string password?;
    string id;
    AuthenticationMode authenticationMode;
    string 'key?;
    string email;
    CustomerGroupReference customerGroup?;
    StoreKeyReference[] stores;
    LastModifiedBy lastModifiedBy?;
    CustomFields custom?;
    string externalId?;
    string dateOfBirth?;
    CustomerGroupAssignment[] customerGroupAssignments;
    string customerNumber?;
    string defaultShippingAddressId?;
    string[] billingAddressIds;
    int version;
    string defaultBillingAddressId?;
    string firstName?;
    CreatedBy createdBy?;
    string middleName?;
    string salutation?;
};

public type FieldDefinition record {
    string name;
    TypeTextInputHint inputHint?;
    LocalizedString label;
    FieldType 'type;
    boolean required;
};

public type CustomerGroupAssignment record {
    CustomerGroupReference customerGroup;
};

public type AttributeDefinitionDraft record {
    boolean isRequired;
    AttributeLevelEnum level?;
    string name;
    AttributeConstraintEnum attributeConstraint?;
    TextInputHint inputHint?;
    LocalizedString label;
    boolean isSearchable?;
    AttributeType 'type;
    LocalizedString inputTip?;
};

public type ProductTypeDraft record {
    string name;
    string description;
    AttributeDefinitionDraft[] attributes?;
    string 'key?;
};

public type TypeDraft record {
    LocalizedString name;
    LocalizedString description?;
    FieldDefinition[] fieldDefinitions?;
    string 'key;
    ResourceTypeId[] resourceTypeIds;
};

# Represents the Queries record for the operation: getCustomObjectByContainerAndKey
public type GetCustomObjectByContainerAndKeyQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

# Represents the Queries record for the operation: deleteProductTypeById
public type DeleteProductTypeByIdQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Expected current version of the resource; the request fails with a concurrency error if it does not match
    int version;
};

public type AttributeType record {
    string name;
};

public type ProductTypeUpdateAction record {
    string action;
};

public type ResourceTypeId "address"|"asset"|"approval-flow"|"approval-rule"|"associate-role"|"business-unit"|"cart-discount"|"category"|"channel"|"customer"|"customer-group"|"custom-line-item"|"discount-code"|"inventory-entry"|"line-item"|"order"|"order-edit"|"order-delivery"|"order-parcel"|"order-return-item"|"payment"|"payment-interface-interaction"|"payment-method"|"payment-method-info"|"product-price"|"product-selection"|"product-tailoring"|"quote"|"reservation"|"review"|"recurring-order"|"shipping"|"shipping-method"|"shopping-list"|"shopping-list-text-line-item"|"standalone-price"|"store"|"transaction";

public type TextInputHint "SingleLine"|"MultiLine";

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    OAuth2ClientCredentialsGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type CreatedBy record {
    *ClientLogging;
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    Attribution attributedTo?;
    CustomerReference associate?;
    CustomerReference customer?;
};

public type CustomObject record {
    *BaseResource;
    string container;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    string id;
    int version;
    anydata value;
    string 'key;
};

public type AttributeConstraintEnum "None"|"Unique"|"CombinationUnique"|"SameForAll";

public type CustomerGroup record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    CustomFields custom?;
    string name;
    string id;
    int version;
    string 'key?;
};

public type ProductType record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    string name;
    string description;
    AttributeDefinition[] attributes?;
    string id;
    int version;
    string 'key?;
};

public type Attribution record {
    string clientId?;
    AttributionSource 'source;
};

# Represents the Queries record for the operation: listCustomObjects
public type ListCustomObjectsQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Number of results to skip, used for pagination. Defaults to 0, maximum 10000
    int offset?;
    # If false, the total count is not calculated, which improves performance of paged queries. Defaults to true
    boolean withTotal?;
    # Number of results to return per page. Defaults to 20, maximum 500
    int 'limit?;
    # Query predicate to filter the results
    string[] 'where?;
    # Sort expression; can be repeated to sort by several fields, for example `createdAt desc`
    string[] sort?;
};

# Represents the Queries record for the operation: deleteCustomObjectByContainerAndKey
public type DeleteCustomObjectByContainerAndKeyQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Expected current version of the resource; the request fails with a concurrency error if it does not match
    int version?;
    # If true, personal data related to the resource is erased from all related resources and logs (GDPR). Defaults to false
    boolean dataErasure?;
};

public type AuthenticationMode "Password"|"ExternalAuth";

public type CustomFields record {
    TypeReference 'type;
    FieldContainer fields;
};

public type CustomerReference record {
    *Reference;
    Customer obj?;
    ReferenceTypeId typeId;
    string id;
};

public type ProductTypePagedQueryResponse record {
    int total?;
    int offset;
    int 'limit;
    int count;
    ProductType[] results;
};

public type CustomObjectPagedQueryResponse record {
    int total?;
    int offset;
    int 'limit;
    int count;
    CustomObject[] results;
};

# Represents the Queries record for the operation: listTypes
public type ListTypesQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Number of results to skip, used for pagination. Defaults to 0, maximum 10000
    int offset?;
    # If false, the total count is not calculated, which improves performance of paged queries. Defaults to true
    boolean withTotal?;
    # Number of results to return per page. Defaults to 20, maximum 500
    int 'limit?;
    # Query predicate to filter the results
    string[] 'where?;
    # Sort expression; can be repeated to sort by several fields, for example `createdAt desc`
    string[] sort?;
};

# Represents the Queries record for the operation: getProductTypeById
public type GetProductTypeByIdQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

# Represents the Queries record for the operation: getTypeById
public type GetTypeByIdQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

# Represents the Queries record for the operation: deleteProductTypeByKey
public type DeleteProductTypeByKeyQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Expected current version of the resource; the request fails with a concurrency error if it does not match
    int version;
};

# Represents the Queries record for the operation: updateTypeByKey
public type UpdateTypeByKeyQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

public type CustomObjectDraft record {
    string container;
    anydata value;
    int version?;
    string 'key;
};

public type TypeUpdateAction record {
    string action;
};

public type LastModifiedBy record {
    *ClientLogging;
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    Attribution attributedTo?;
    CustomerReference associate?;
    CustomerReference customer?;
};

# Represents the Queries record for the operation: getTypeByKey
public type GetTypeByKeyQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

# Represents the Queries record for the operation: updateProductTypeByKey
public type UpdateProductTypeByKeyQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

public type AttributeDefinition record {
    boolean isRequired;
    AttributeLevelEnum level;
    string name;
    AttributeConstraintEnum attributeConstraint;
    TextInputHint inputHint;
    LocalizedString label;
    boolean isSearchable;
    AttributeType 'type;
    LocalizedString inputTip?;
};

public type LocalizedString record {|
    string...;
|};

# Represents the Queries record for the operation: listProductTypes
public type ListProductTypesQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Number of results to skip, used for pagination. Defaults to 0, maximum 10000
    int offset?;
    # If false, the total count is not calculated, which improves performance of paged queries. Defaults to true
    boolean withTotal?;
    # Number of results to return per page. Defaults to 20, maximum 500
    int 'limit?;
    # Query predicate to filter the results
    string[] 'where?;
    # Sort expression; can be repeated to sort by several fields, for example `createdAt desc`
    string[] sort?;
};

# Represents the Queries record for the operation: createProductType
public type CreateProductTypeQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

public type AttributionSource "Import"|"Export";

# Represents the Queries record for the operation: createType
public type CreateTypeQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

public type CustomerGroupReference record {
    *Reference;
    CustomerGroup obj?;
    ReferenceTypeId typeId;
    string id;
};

# Represents the Queries record for the operation: getProductTypeByKey
public type GetProductTypeByKeyQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

# Represents the Queries record for the operation: deleteTypeById
public type DeleteTypeByIdQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Expected current version of the resource; the request fails with a concurrency error if it does not match
    int version;
};

public type TypeReference record {
    *Reference;
    Type obj?;
    ReferenceTypeId typeId;
    string id;
};

public type CountryCode string;

public type FieldContainer record {|
    string...;
|};

# Represents the Queries record for the operation: updateProductTypeById
public type UpdateProductTypeByIdQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

# Represents the Queries record for the operation: deleteTypeByKey
public type DeleteTypeByKeyQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Expected current version of the resource; the request fails with a concurrency error if it does not match
    int version;
};

public type TypeTextInputHint "SingleLine"|"MultiLine";

public type Reference record {
    ReferenceTypeId typeId;
    string id;
};

public type ClientLogging record {
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    CustomerReference associate?;
    CustomerReference customer?;
};

public type AttributeLevelEnum "Product"|"Variant";

# Represents the Queries record for the operation: updateTypeById
public type UpdateTypeByIdQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};

public type BaseResource record {
    string createdAt;
    string lastModifiedAt;
    string id;
    int version;
};

public type ProductTypeUpdate record {
    int version;
    ProductTypeUpdateAction[] actions;
};

public type TypePagedQueryResponse record {
    int total?;
    int offset;
    int 'limit;
    int count;
    Type[] results;
};

public type ReferenceTypeId "approval-flow"|"approval-rule"|"associate-role"|"attribute-group"|"business-unit"|"cart"|"cart-discount"|"category"|"channel"|"customer"|"customer-email-token"|"customer-group"|"customer-password-token"|"direct-discount"|"discount-code"|"discount-group"|"extension"|"inventory-entry"|"key-value-document"|"mcp-server"|"order"|"order-edit"|"payment-method"|"payment"|"product"|"product-discount"|"product-price"|"product-selection"|"product-tailoring"|"product-type"|"quote"|"quote-request"|"recurrence-policy"|"recurring-order"|"reservation"|"review"|"shipping-method"|"shopping-list"|"staged-quote"|"standalone-price"|"state"|"store"|"subscription"|"tax-category"|"type"|"variant"|"zone";

public type TypeUpdate record {
    int version;
    TypeUpdateAction[] actions;
};

public type BaseAddress record {
    CountryCode country;
    string lastName?;
    string city?;
    string postalCode?;
    string title?;
    string building?;
    string streetName?;
    string company?;
    string id?;
    string state?;
    string department?;
    string fax?;
    string 'key?;
    string email?;
    string pOBox?;
    string streetNumber?;
    string mobile?;
    string externalId?;
    string additionalAddressInfo?;
    string firstName?;
    string phone?;
    string additionalStreetInfo?;
    string salutation?;
    string region?;
    string apartment?;
};

public type FieldType record {
    string name;
};

# Represents the Queries record for the operation: listCustomObjectsByContainer
public type ListCustomObjectsByContainerQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
    # Number of results to skip, used for pagination. Defaults to 0, maximum 10000
    int offset?;
    # If false, the total count is not calculated, which improves performance of paged queries. Defaults to true
    boolean withTotal?;
    # Number of results to return per page. Defaults to 20, maximum 500
    int 'limit?;
    # Query predicate to filter the results
    string[] 'where?;
    # Sort expression; can be repeated to sort by several fields, for example `createdAt desc`
    string[] sort?;
};

public type Type record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    LocalizedString name;
    LocalizedString description?;
    FieldDefinition[] fieldDefinitions;
    string id;
    int version;
    string 'key;
    ResourceTypeId[] resourceTypeIds;
};

# Represents the Queries record for the operation: createOrUpdateCustomObject
public type CreateOrUpdateCustomObjectQueries record {
    # A field to expand. Reference fields can be expanded to include the referenced resource inline
    string[] expand?;
};
